#!/usr/bin/env python3
"""Zero-config bio-ship cost regenerator for gk_lithogenesis.

Walks vanilla Stellaris source, detects bio-ship components/inline_scripts with
food costs, rewrites them with the paired-trigger food/minerals pattern, and
writes the output under gk_lithogenesis/. Run after every vanilla update.

Detection rules (no configuration):
  inline_scripts: glob common/inline_scripts/ship_components/bio_*.txt
  component_templates: glob common/component_templates/*.txt, per top-level block
    match on bio-ship signals (country_uses_bio_ships / is_galvanic_empire /
    ship_uses_weaver_components) AND food in resources.

Outputs:
  inline_scripts: mirror vanilla relative path
  component_templates: aggregated into common/component_templates/zz_flgsis_generated_components.txt
"""

from __future__ import annotations

import argparse
import glob
import os
import sys
from pathlib import Path

import pdxscript as p
import transform as t


DEFAULT_VANILLA = Path.home() / ".steam/steam/steamapps/common/Stellaris"
DEFAULT_MOD = Path("/home/ryn/Projects/Stellaris/mod/gk_lithogenesis")

GENERATED_HEADER = (
    "# GENERATED by tools/gk_lithogen/generate.py from vanilla {source}.\n"
    "# Do not hand-edit — re-run the script after vanilla updates.\n"
)

COMPONENT_OUTPUT_PREFIX = "!flgsis_"


def process_inline_scripts(vanilla: Path, mod: Path, dry_run: bool) -> int:
    """Regenerate each bio_*.txt inline_script. Returns count of files written."""
    src_glob = vanilla / "common/inline_scripts/ship_components/bio_*.txt"
    out_dir = mod / "common/inline_scripts/ship_components"
    count = 0
    for src_path in sorted(glob.glob(str(src_glob))):
        src_rel = Path(src_path).name
        try:
            ast = p.parse_file(src_path)
        except Exception as e:
            print(f"[skip] parse error in {src_rel}: {e}", file=sys.stderr)
            continue
        t.rebase_food_to_minerals(ast)
        body = p.write(ast)
        header = GENERATED_HEADER.format(
            source=f"common/inline_scripts/ship_components/{src_rel}"
        )
        out = header + body
        out_path = out_dir / src_rel
        if dry_run:
            print(f"[dry] {out_path} ({len(body)} bytes)")
        else:
            out_dir.mkdir(parents=True, exist_ok=True)
            out_path.write_text(out, encoding="utf-8")
            print(f"[wrote] {out_path}")
        count += 1
    return count


def process_component_templates(vanilla: Path, mod: Path, dry_run: bool) -> int:
    """Scan component_templates for bio-relevant blocks, rebase, write per-file output.

    One output file per vanilla source file that yields matching blocks. Each
    output preserves the source file's top-level @var assignments (file-scoped
    macros that the rebased templates may reference). Output filename is the
    vanilla filename with a zz_flgsis_ prefix so it loads after hand-authored
    overwrites and after vanilla.

    Returns total count of blocks rebased across all files.
    """
    src_glob = vanilla / "common/component_templates/*.txt"
    out_dir = mod / "common/component_templates"
    total_blocks = 0
    scanned_files = 0
    files_written = 0
    for src_path in sorted(glob.glob(str(src_glob))):
        fname = Path(src_path).name
        try:
            ast = p.parse_file(src_path)
        except Exception as e:
            print(f"[skip] parse error in {fname}: {e}", file=sys.stderr)
            continue
        scanned_files += 1
        # Files named 00_biogenesis_*.txt are 100% bio-ship content by Paradox
        # convention. Components in them (growth/booster/etc.) sometimes gate on
        # is_ship_size rather than country_uses_bio_ships, so the per-block
        # structural check misses them. Treat every template in those files as
        # bio-qualifying, filter on food presence alone.
        file_is_bio = fname.startswith("00_biogenesis_")
        matching_blocks = []
        # Top-level @var assignments are file-scoped; templates may reference them.
        at_vars = []
        for child in ast.children:
            if isinstance(child, p.Assign):
                if child.key.startswith("@"):
                    at_vars.append(child)
                elif child.key in (
                    "utility_component_template",
                    "weapon_component_template",
                    "strike_craft_component_template",
                ):
                    is_bio = file_is_bio or t.is_bio_ship_block(child)
                    if is_bio and t.has_food_resource(child):
                        t.rebase_food_to_minerals(child.value)
                        matching_blocks.append(child)
        if not matching_blocks:
            continue
        out_root = p.Block([])
        # Carry over all @ variables (we include the whole set; pruning unused ones
        # is a premature optimization and risks breaking cross-reference chains).
        out_root.children.extend(at_vars)
        out_root.children.extend(matching_blocks)
        header = GENERATED_HEADER.format(source=f"common/component_templates/{fname}")
        out_text = header + p.write(out_root)
        out_path = out_dir / (COMPONENT_OUTPUT_PREFIX + fname)
        if dry_run:
            print(f"[dry] {out_path} ({len(matching_blocks)} block(s), {len(at_vars)} @var(s))")
        else:
            out_dir.mkdir(parents=True, exist_ok=True)
            out_path.write_text(out_text, encoding="utf-8")
            print(f"[wrote] {out_path} ({len(matching_blocks)} block(s), {len(at_vars)} @var(s))")
        total_blocks += len(matching_blocks)
        files_written += 1
    if total_blocks == 0:
        print(f"[info] no matching component_template blocks (scanned {scanned_files} files)")
    return total_blocks


def main() -> int:
    ap = argparse.ArgumentParser(description="Regenerate gk_lithogenesis bio-ship cost overwrites from vanilla.")
    ap.add_argument("--vanilla", type=Path, default=DEFAULT_VANILLA,
                    help=f"Vanilla Stellaris install (default: {DEFAULT_VANILLA})")
    ap.add_argument("--mod", type=Path, default=DEFAULT_MOD,
                    help=f"gk_lithogenesis mod root (default: {DEFAULT_MOD})")
    ap.add_argument("--dry-run", action="store_true",
                    help="Print what would be written without touching disk.")
    args = ap.parse_args()

    if not (args.vanilla / "common").is_dir():
        print(f"error: --vanilla {args.vanilla} doesn't look like a Stellaris install", file=sys.stderr)
        return 2
    if not (args.mod / "descriptor.mod").is_file():
        print(f"error: --mod {args.mod} doesn't have descriptor.mod", file=sys.stderr)
        return 2

    n_scripts = process_inline_scripts(args.vanilla, args.mod, args.dry_run)
    n_blocks = process_component_templates(args.vanilla, args.mod, args.dry_run)
    print(f"\nSummary: {n_scripts} inline_scripts regenerated, {n_blocks} component blocks rebased.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
